AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Application Template: This template provisions an EC2 autoscaling group in 2 VPC Subnets provisioned in a different stack.

# This template creates:
#   Amazon EC2 instance
#   Security Group

######################
# Parameters section
######################

Parameters:

  NetworkStackName:
    Description: >-
      Name of an active CloudFormation stack that contains the networking
      resources, such as the VPC and subnet that will be used in this stack.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: nw-stack

  AmazonLinuxAMIID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

######################
# Resources section
######################

Resources:

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP ingress
      VpcId:
        Fn::ImportValue:
          !Sub '${NetworkStackName}-VPC-ID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Web Server Security Group

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    DependsOn: WebServerSecurityGroup
    Properties:
      LaunchTemplateName: Web-LT
      LaunchTemplateData:
        ImageId: !Ref AmazonLinuxAMIID
        InstanceType: t2.micro
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            sudo yum update -y
            sudo amazon-linux-extras install nginx1 -y 
            sudo systemctl enable nginx
            sudo systemctl start nginx
        NetworkInterfaces: 
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          Groups:
          - !Ref WebServerSecurityGroup

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: LaunchTemplate
    Properties: 
      AutoScalingGroupName: WebASG
      # AvailabilityZones: 
      #   - us-east-1a
      #   - us-east-1b
      DesiredCapacity: '2'
      MaxSize: '4'
      MinSize: '2'
      VPCZoneIdentifier: 
        - Fn::ImportValue: 'nw-stack-Subnet1-ID'
        - Fn::ImportValue: 'nw-stack-Subnet2-ID'
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber

